require:
  - rubocop-rspec
  - rubocop-rails
#
# #    _____               ____ ____        __     _         __
# #   / ___/ _____ ____ _ / __// __/____   / /    (_)____   / /_
# #   \__ \ / ___// __ `// /_ / /_ / __ \ / /    / // __ \ / __/
# #  ___/ // /__ / /_/ // __// __// /_/ // /___ / // / / // /_
# # /____/ \___/ \__,_//_/  /_/ 1 \____//_____//_//_/ /_/ \__/
# #
# # The linter file that doesn't lead junior developers to bad habits.
# # https://github.com/makersacademy/scaffolint
# #
# # Configure Rubocop to use the config file in the Scaffolint GitHub repo
# inherit_from:
#   - https://raw.githubusercontent.com/makersacademy/scaffolint/v1.1.0/.rubocop.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/DescribeClass:
  Exclude:
      - spec/features/**/*

RSpec/Be:
  Enabled: false