version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      auth:
          username: ptpeeps
          password: returnofthepeeps
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
      auth:
          username: ptpeeps
          password: returnofthepeeps
      environment:
        POSTGRES_DB: pgapp_test
    environment:
      PGHOST: 127.0.0.1
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

