# version: 2.1
# orbs:
#   ruby: circleci/ruby@0.1.2 

# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.6.3-stretch-node
#         auth:
#           username: ptpeeps
#           password: returnofthepeeps
#     executor: ruby/default
#     steps:
#       - checkout
#       - run:
#         name: Which bundler?
#         command: bundle -v
#       - ruby/bundle-install
#   test:
#     docker:
#       - image: circleci/ruby:2.6.3-stretch-node
#         auth:
#           username: ptpeeps
#           password: returnofthepeeps
#         environment:
#           POSTGRES_DB: pgapp_test
#     environment:
#       PGHOST: 127.0.0.1
#       RAILS_ENV: test
#     steps:
#       - checkout
#       - run:
#           name: Wait for DB
#           command: dockerize -wait tcp://localhost:5432 -timeout 1m
#       - run:
#           name: Database setup
#           command: bundle exec rails db:schema:load --trace
#       - ruby/rspec-test


version: 2.1 

orbs:
  ruby: circleci/ruby@1.0 

jobs:
  build: 
    docker:
      - image: cimg/ruby:2.7-node
        auth:
          username: ptpeeps
          password: returnofthepeeps 
    steps:
      - checkout
      - ruby/install-deps
          
  test:
    docker:
      - image: cimg/ruby:2.7-node
        auth:
          username: ptpeeps
          password: returnofthepeeps 
      - image: circleci/postgres:9.5-alpine
        auth:
          username: ptpeeps
          password: returnofthepeeps 
        environment:
          POSTGRES_USER: student
          POSTGRES_DB: pgapp_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build         # Run build first.
      - test:         # Then run test,
          requires:   # Test requires that build passes for it to run.
            - build 
